# Generated by Django 5.2.4 on 2025-08-25 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Nuevo Ticket Creado'), ('ticket_updated', 'Ticket Actualizado'), ('ticket_closed', 'Ticket Cerrado'), ('message_created', 'Nuevo Mensaje'), ('assessment_completed', 'Autoevaluación Completada')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ticket_created', models.BooleanField(default=True)),
                ('email_ticket_updated', models.BooleanField(default=True)),
                ('email_ticket_closed', models.BooleanField(default=True)),
                ('email_message_created', models.BooleanField(default=True)),
                ('email_assessment_completed', models.BooleanField(default=True)),
                ('web_ticket_created', models.BooleanField(default=True)),
                ('web_ticket_updated', models.BooleanField(default=True)),
                ('web_ticket_closed', models.BooleanField(default=True)),
                ('web_message_created', models.BooleanField(default=True)),
                ('web_assessment_completed', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
    ]
